name: Svelte Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run svelte checks
        run: npm run check
